### ISSUE TITLE
Found bug in win-checking

### ISSUE THREAD

**Issue by eswan18** [8451-CS-Club/connect-four#1]
a board with all 'R's in the bottom row and all 'Y's in the second-to-bottom row does not register as a win

**Comment by dschuler36** [comment]
what's the player moves you're using to replicate this error? I'm not 100% sure how to test some of these scenarios currently

**Comment by eswan18** [comment]
If you use the main2.py file, you can manually input moves. I did:
R - 1, Y - 1
R - 2, Y - 2
R - 3, Y - 3
R - 4, Y - 4
R - 5, Y - 5
R - 6, Y - 6

So R and Y both have full rows, but no winner is found

**Comment by eswan18** [comment]
Fixed

**Comment by eswan18** [comment]
Fixed
